parameters:
    amqp_currency_rate_sync_dsn: '%env(MESSENGER_TRANSPORT_DSN)%/%2f/sync_currency_rates'
    amqp_currency_rate_sync_failed_dsn: '%env(MESSENGER_TRANSPORT_DSN)%/%2f/sync_currency_rates_failed'

framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - doctrine_ping_connection

        transports:
            amqp_currency_rate_sync:
                dsn: '%amqp_currency_rate_sync_dsn%'
                failure_transport: amqp_currency_rate_sync_failed
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            amqp_currency_rate_sync_failed:
                dsn: '%amqp_currency_rate_sync_failed_dsn%'
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2

        routing:
            App\Application\CurrencyExchangeRate\CreateCurrencyExchangeRateCommand: amqp_currency_rate_sync
