parameters:


services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'
    _instanceof:
        # Command Handlers
        App\Infrastructure\Messenger\CommandBus\CommandHandlerInterface:
            tags: [ { name: messenger.message_handler, bus: messenger.bus.commands } ]

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    # Command Bus
    App\Infrastructure\Messenger\CommandBus\CommandBus:
        arguments: [ '@messenger.bus.commands' ]
    App\Infrastructure\Messenger\CommandBus\CommandBusInterface: '@App\Infrastructure\Messenger\CommandBus\CommandBus'
